/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hyperledger.fabric;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'org.hyperledger.fabric.greeting' plugin.
 */
public class ChaincodePackagePluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        // Project project = ProjectBuilder.builder().build();
        // project.getPlugins().apply("org.hyperledger.fabric.chaincodepackage");

        // System.out.println(project.getTasks().toString());
        // // Verify the result
        // assertNotNull(project.getTasks().findByName("chaincodePackage"));
    }
}
