/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hyperledger.fabric;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class ChaincodePackagePlugin implements Plugin<Project> {


    @Override
    public void apply(Project project) {
        project.getExtensions().create("chaincodePackage",
                ChaincodePackageExtension.class);

        project.getTasks().register("chaincodePackage", ChaincodePackageTask.class);
    }
}